export const DISPUTE_REASONS = {
  WORK_NOT_DELIVERED: 'WORK_NOT_DELIVERED',
  WORK_LOW_QUALITY: 'WORK_LOW_QUALITY',
  DEADLINE_MISSED: 'DEADLINE_MISSED',
  CLIENT_UNRESPONSIVE: 'CLIENT_UNRESPONSIVE',
  FREELANCER_UNRESPONSIVE: 'FREELANCER_UNRESPONSIVE',
  SCOPE_MISMATCH: 'SCOPE_MISMATCH',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  MUTUAL_CANCEL: 'MUTUAL_CANCEL',
  CLIENT_UNFAIR_CANCELLATION: 'CLIENT_UNFAIR_CANCELLATION',
  OTHER: 'OTHER',
} as const;

export type DisputeReasonCode = (typeof DISPUTE_REASONS)[keyof typeof DISPUTE_REASONS];

export const DISPUTE_REASON_LABELS: Record<string, string> = {
  WORK_NOT_DELIVERED: 'Work Not Delivered',
  WORK_LOW_QUALITY: 'Work Low Quality',
  DEADLINE_MISSED: 'Deadline Missed',
  CLIENT_UNRESPONSIVE: 'Client Unresponsive',
  FREELANCER_UNRESPONSIVE: 'Freelancer Unresponsive',
  SCOPE_MISMATCH: 'Scope Mismatch',
  PAYMENT_ISSUE: 'Payment Issue',
  MUTUAL_CANCEL: 'Mutual Cancel',
  CLIENT_UNFAIR_CANCELLATION: 'Client Unfair Cancellation',
  OTHER: 'Other',
};
