const clientRouterEndPoints = {
  me: "/client/me",
  dashboard: "/client/dashboard",
  finance: "/client/finance",
  updateClient: "/client/update",
  getAllCategories: "/client/categories",
  getSpecialitiesWithSkills: "/client/specialities",
  createJob: "/client/jobs",
  getAllJobs: "/client/jobs",
  getJobDetail: (jobId:string)=>`/client/jobs/${jobId}`,
  updateJobDetail:(jobId:string)=>`/client/jobs/${jobId}`,
  closeJob: (jobId:string)=>`/client/jobs/${jobId}/close`,
  getAllFreelancers:"/client/freelancers",
  getFreelancerDetail:(freelancerId:string)=>`/client/freelancers/${freelancerId}`,
  saveFreelancer:(freelancerId:string)=>`/client/freelancers/${freelancerId}/save`,
  isFreelancerSaved:(freelancerId:string)=>`/client/freelancers/${freelancerId}/saved`,
  getSavedFreelancers: "/client/saved-freelancers",
  createOffer: "/client/offers",
  getOffers: "/client/offers",
  getOfferDetail: (offerId: string) => `/client/offers/${offerId}`,
  withdrawOffer: (offerId: string) => `/client/offers/${offerId}/withdraw`,
  getAllFreelancerPortfolio:(freelancerId:string)=>`/client/freelancers/${freelancerId}/portfolio`,
  getAllJobProposals:(jobId:string)=>`/client/jobs/${jobId}/proposals`,
  getProposalDetail:(proposalId:string)=>`/client/proposals/${proposalId}`,
  rejectProposal:(proposalId:string)=>`/client/proposals/${proposalId}/reject`,
  getContracts:"/client/contracts",
  getContractDetail:(contractId:string)=>`/client/contracts/${contractId}`,
  cancelContract:(contractId:string)=>`/client/contracts/${contractId}/cancel`,
  cancelContractWithDispute: (contractId: string) => `/client/contracts/${contractId}/cancel-with-dispute`,
  createDispute: "/client/disputes",
  getDisputeById: (disputeId: string) => `/client/disputes/${disputeId}`,
  getDisputesByContract: (contractId: string) => `/client/contracts/${contractId}/disputes`,
  initiatePayment:"/client/payments/initiate",
  paymentCallback:"/client/payments/callback",
  sendChatMessage: "/client/chat/send",
  getChatMessages: (contractId: string) => `/client/chat/${contractId}/messages`,
  markChatAsRead: "/client/chat/read",
  getChatUnreadCount: (contractId: string) => `/client/chat/${contractId}/unread-count`,
  getMilestoneDetail: (contractId: string, milestoneId: string) => `/client/contracts/${contractId}/milestones/${milestoneId}`,
  approveDeliverable: (contractId: string) => `/client/contracts/${contractId}/deliverables/approve`,
  requestDeliverableChanges: (contractId: string) => `/client/contracts/${contractId}/deliverables/request-changes`,
  approveMilestoneDeliverable: (contractId: string) => `/client/contracts/${contractId}/milestones/deliverables/approve`,
  requestMilestoneChanges: (contractId: string) => `/client/contracts/${contractId}/milestones/deliverables/request-changes`,
  respondToMilestoneExtension: (contractId: string) => `/client/contracts/${contractId}/milestones/extension/respond`,
  respondToContractExtension: (contractId: string) => `/client/contracts/${contractId}/extension/respond`,
  getContractWorklogs: (contractId: string) => `/client/contracts/${contractId}/worklogs`,
  getWorklogDetail: (contractId: string, worklogId: string) => `/client/contracts/${contractId}/worklogs/${worklogId}`,
  approveWorklog: (contractId: string) => `/client/contracts/${contractId}/worklogs/approve`,
  rejectWorklog: (contractId: string) => `/client/contracts/${contractId}/worklogs/reject`,
  proposeMeeting: (contractId: string) => `/client/contracts/${contractId}/meetings`,
  getContractMeetings: (contractId: string) => `/client/contracts/${contractId}/meetings`,
  acceptMeeting: '/client/meetings/accept',
  rejectMeeting: '/client/meetings/reject',
  approveReschedule: '/client/meetings/reschedule/approve',
  declineReschedule: '/client/meetings/reschedule/decline',
  requestMeetingReschedule: '/client/meetings/reschedule',
  downloadDeliverableFiles: (contractId: string) => `/client/contracts/${contractId}/deliverables/download`,
  downloadMilestoneDeliverableFiles: (contractId: string, milestoneId: string) => `/client/contracts/${contractId}/milestones/${milestoneId}/deliverables/download`,
  submitReview: (contractId: string) => `/client/contracts/${contractId}/review`,
  getReviewStatus: (contractId: string) => `/client/contracts/${contractId}/review/status`,
  getFreelancerReviews: (freelancerId: string) => `/client/freelancers/${freelancerId}/reviews`,
  activateHourlyContract: (contractId: string) => `/client/contracts/${contractId}/activate`,
  endHourlyContract: (contractId: string) => `/client/contracts/${contractId}/end`,
  joinMeet: (meetingId: string) => `/client/meetings/${meetingId}/join`,
};

export default clientRouterEndPoints;
