import { get } from "lodash";

const freelancerRouterEndPoints = {
  //me
  me: "/freelancer/me",
  updateLanguage: "/freelancer/profile/language",
  deleteLanguage: "/freelancer/profile/language",
  deleteEducation: "/freelancer/profile/education",
  deletePortfolio: "/freelancer/profile/portfolio",
  deleteWorkHistory: "/freelancer/profile/workHistory",
  updateDescription: "/freelancer/profile/description",
  updateProfessionalRole: "/freelancer/profile/professionalRole",
  updateHourlyRate: "/freelancer/profile/hourlyRate",
  updateEducation: "/freelancer/profile/education",
  updateWorkHistory: "/freelancer/profile/workHistory",
  createPortfolio: "/freelancer/portfolio",
  getPortfolio: "/freelancer/portfolio",
  getPortfolioDetails: "/freelancer/portfolio/detail",
  getAllCategories: "/freelancer/categories",
  getSpecialitiesWithSkills: "/freelancer/specialities",
  getJobs: "/freelancer/jobs",
  getJobDetail:(jobId:string)=> `/freelancer/jobs/${jobId}`,
  saveJob: (jobId: string) => `/freelancer/jobs/${jobId}/save`,
  isJobSaved: (jobId: string) => `/freelancer/jobs/${jobId}/saved`,
  reportJob: (jobId: string) => `/freelancer/jobs/${jobId}/report`,
  isJobReported: (jobId: string) => `/freelancer/jobs/${jobId}/reported`,
  getSavedJobs: () => `/freelancer/saved-jobs`,
  createProposal:'/freelancer/proposals',
  getMyProposals:(jobId:string)=> `/freelancer/jobs/${jobId}/proposals`,
  getOffers: '/freelancer/offers',
  getOfferDetail: (offerId: string) => `/freelancer/offers/${offerId}`,
  rejectOffer: (offerId: string) => `/freelancer/offers/${offerId}/reject`,
  acceptOffer: (offerId: string) => `/freelancer/offers/${offerId}/accept`,
  getContracts: '/freelancer/contracts',
  getContractDetail: (contractId: string) => `/freelancer/contracts/${contractId}`,
  getContractTimeline: (contractId: string) => `/freelancer/contracts/${contractId}/timeline`,
  getCancellationRequest: (contractId: string) => `/freelancer/contracts/${contractId}/cancellation-request`,
  acceptCancellationRequest: (contractId: string) => `/freelancer/contracts/${contractId}/cancellation-request/accept`,
  raiseCancellationDispute: (contractId: string) => `/freelancer/contracts/${contractId}/cancellation-request/raise-dispute`,
  createCancellationRequest: (contractId: string) => `/freelancer/contracts/${contractId}/cancellation-request`,
  cancelContract: (contractId: string) => `/freelancer/contracts/${contractId}/cancel`,
  cancelContractWithDispute: (contractId: string) => `/freelancer/contracts/${contractId}/cancel-with-dispute`,
  endHourlyContract: (contractId: string) => `/freelancer/contracts/${contractId}/end`,
  createDispute: "/freelancer/disputes",
  getDisputeById: (disputeId: string) => `/freelancer/disputes/${disputeId}`,
  getDisputesByContract: (contractId: string) => `/freelancer/contracts/${contractId}/disputes`,
  raiseDisputeForCancelledContract: (contractId: string) => `/freelancer/contracts/${contractId}/raise-dispute`,
  submitContractDeliverable: (contractId: string) => `/freelancer/contracts/${contractId}/deliverables`,
  submitMilestoneDeliverable: (contractId: string) => `/freelancer/contracts/${contractId}/milestones/deliverables`,
  requestMilestoneExtension: (contractId: string) => `/freelancer/contracts/${contractId}/milestones/extension`,
  requestContractExtension: (contractId: string) => `/freelancer/contracts/${contractId}/extension`,
  submitWorklog: "/freelancer/worklogs",
  getContractWorklogs: (contractId: string) => `/freelancer/contracts/${contractId}/worklogs`,
  getContractWorklogsList: (contractId: string) => `/freelancer/contracts/${contractId}/worklogs/list`,
  getWorklogDetail: (contractId: string, worklogId: string) => `/freelancer/contracts/${contractId}/worklogs/${worklogId}`,
  checkWorklogValidation: (contractId: string) => `/freelancer/contracts/${contractId}/worklog-validation`,
  raiseWorklogDispute: (contractId: string) => `/freelancer/contracts/${contractId}/worklogs/raise-dispute`,
  updateExpertise: '/freelancer/profile/expertise',
  sendChatMessage: "/freelancer/chat/send",
  getChatMessages: (contractId: string) => `/freelancer/chat/${contractId}/messages`,
  markChatAsRead: "/freelancer/chat/read",
  getChatUnreadCount: (contractId: string) => `/freelancer/chat/${contractId}/unread-count`,
  getMeetings: '/freelancer/meetings',
  getMeetingDetail: (meetingId: string) => `/freelancer/meetings/${meetingId}`,
  getContractMeetings: (contractId: string) => `/freelancer/contracts/${contractId}/meetings`,
  getAllFreelancerMeetings: '/freelancer/meetings',
  acceptMeeting: '/freelancer/meetings/accept',
  requestMeetingReschedule: '/freelancer/meetings/reschedule',
  requestMeetingReject: '/freelancer/meetings/reject',
  approveReschedule: '/freelancer/meetings/reschedule/approve',
  declineReschedule: '/freelancer/meetings/reschedule/decline',
  counterReschedule: '/freelancer/meetings/reschedule/counter',
  proposeMeeting: (contractId: string) => `/freelancer/contracts/${contractId}/meetings`,
  joinMeet: (meetingId: string) => `/freelancer/meetings/${meetingId}/join`,
  submitReview: (contractId: string) => `/freelancer/contracts/${contractId}/review`,
  getReviewStatus: (contractId: string) => `/freelancer/contracts/${contractId}/review/status`,
  getMyReviews: '/freelancer/reviews',
  getEarningsOverview: '/freelancer/earnings/overview',
  getTransactions: '/freelancer/earnings/transactions',
  getDashboardContractStats: '/freelancer/dashboard/contract-stats',
  getDashboardEarnings: '/freelancer/dashboard/earnings',
  // finance
  finance: '/freelancer/finance',
  financeWithdraw: '/freelancer/finance/withdraw',
  financeWithdrawals: '/freelancer/finance/withdrawals',
  financeWithdrawalDetail: (withdrawalId: string) => `/freelancer/finance/withdrawals/${withdrawalId}`,
  getDashboardMeetings: '/freelancer/dashboard/meetings',
  getDashboardReviewStats: '/freelancer/dashboard/review-stats',
  approveDeliverableChanges: (contractId: string, deliverableId: string) => `/freelancer/contracts/${contractId}/deliverables/${deliverableId}/approve-change`,
  getNotifications: "/freelancer/notifications",
  markNotificationAsRead: (notificationId: string) => `/freelancer/notifications/${notificationId}/read`,
  markAllNotificationsAsRead: "/freelancer/notifications/read-all",
};

export default freelancerRouterEndPoints;
